
spring:
  application:
    name: book-client

grpc:
  client:
    book-client:
      address: 'static://localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

